In [57]:
import numpy as np

In [2]:
l = range(100)
print(l)

range(0, 100)


In [4]:
d = np.arange(100)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [3]:
x = np.arange(1,13).reshape((6,2))
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [3]:
x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))
x

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [13]:
a = np.arange(1, 100*10+1).reshape((100,10))
x = a[a%5==0]
x = x[x%7 ==0]
x

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [17]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1, 0]] = arr[:, [0, 1]]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [20]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr = np.zeros(10)
arr[5], arr[8] = 10,20
arr

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

In [30]:
arr = np.zeros(4, dtype=np.int64)
arr

array([0, 0, 0, 0])

In [32]:
np.full((2,5), fill_value=6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [33]:
np.arange(start=2, stop=100, step=2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [53]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])

arr - brr[:,None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ans = arr.copy()
ans[ans%2 == 1] = -1
ans

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [54]:
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    a = np.arange(start=2, stop=102, step=2) # write your code here
    return a

In [55]:
function9()

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [94]:
arr = np.array([1,2,3])
ans = np.concatenate((np.repeat(arr,3), np.tile(arr,3)))
ans

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [106]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])
ans = np.logical_and(arr>=5, arr<=10)
ans

array([False,  True, False,  True,  True, False, False])